### ISSUE TITLE
Arrows are in the wrong position horizontally

### ISSUE THREAD

**Issue by Tatsh** [Tatsh/tapmania#1]
Left is under down target

**Comment by godexsoft** [comment]
Great job on resurrecting the project 👍 Randomly stumbled upon your fork. Pleased to see the project lives on (kind of at least). The power of opensource 🥇

**Comment by Tatsh** [comment]
Yeah at this point I'm leaving this hopefully working for now in the develop branch. My plan is to port StepMania to iOS unofficially.

**Comment by godexsoft** [comment]
Porting stepmania is little more work than tapmania i imagine :) I have ported parts of stepmania into tapmania back in the day (like the file format support etc.) but that was more a rewrite than a copy-paste. I'll give your dev branch a go 👍
